# GET http://localhost:8000/todos
GET https://todo-api-ujbe.onrender.com/todos


###
# POST http://localhost:8000/todo/new
POST https://todo-api-ujbe.onrender.com/todo/new
Content-Type: application/json
{
    "text":"Welcome in Atpadi"
}

###
# DELETE http://localhost:8000/todo/delete/63de71539e5a7b381e7b6a2e
DELETE https://todo-api-ujbe.onrender.com/todo/delete/63de71539e5a7b381e7b6a2e

###

# GET http://localhost:8000/todo/complete/63de714a9e5a7b381e7b6a2c
GET https://todo-api-ujbe.onrender.com/todo/complete/63de714a9e5a7b381e7b6a2c

###

# PUT http://localhost:8000/todo/update/63de714a9e5a7b381e7b6a2c
PUT https://todo-api-ujbe.onrender.com/todo/update/63de714a9e5a7b381e7b6a2c


